matrix:
  include:
    - language: python
      python: 
        - "3.6"
        - "3.4"

      cache: pip

      before_install:
        - cd api-server/

      install:
        - pip install -r requirements.txt
        - psql -c 'create database metawahl;' -U postgres
        - python models.py --force
        - python bootstrap_db.py

      env:
        METAWAHL_CONFIG=test.conf.py

      script:
        - ./travis_tavern.sh

    - language: node_js
      node_js:
        - 8
        - 9

      before_install:
        - cd client/

      cache:
        directories:
          - "node_modules"

      script:
        - npm run build
        - npm test