matrix:
  include:
    - language: python
      python: 3.6

      env: METAWAHL_CONFIG=test.conf.py
      cache: pip

      before_install:
        - cd api/

      install:
        - pip install pipenv
        - pipenv sync
        - psql -c 'create database metawahl;' -U postgres
        - pipenv run python scripts/reset_db.py --force
        - pipenv run python scripts/bootstrap_db.py

      script: pipenv run ./travis_tavern.sh

    - language: node_js
      node_js:
        - 9
        - 10

      before_install: cd client/

      script:
        - yarn run build
        - yarn test

      cache:
        directories:
          - "node_modules"
