matrix:
  include:
    - language: python
      python: 3.6

      env: METAWAHL_CONFIG=test.conf.py
      cache: pip

      before_install:
        - cd api-server/

      install:
        - pip install pipenv
        - pipenv sync
        - psql -c 'create database metawahl;' -U postgres
        - python models.py --force
        - python bootstrap_db.py

      script: ./travis_tavern.sh

    - language: node_js
      node_js:
        - 9
        - 10

      before_install: cd client/

      script:
        - yarn run build
        - yarn test

      cache:
        directories:
          - "node_modules"
