matrix:
  include:
    - language: python
      python: 3.6

      before_install:
        - cd api-server/

      install:
        - pip install -r requirements.txt

      script:
        - pytest

      env:
        METAWAHL_CONF=prod.conf.py
        ADMIN_KEY=asdfyooo

    - language: node_js
      node_js:
        - 8
        - 9

      before_install:
        - cd client/

      cache:
        directories:
          - "node_modules"

      script:
        - npm run build
        - npm test